# If the page function class name is not the same as the calling function name, we need to map them.
# If add new page function .py file, it is neccessary to add the mapping here.

class_mapping = {
            "basepage": "main_page",
            "Main_Page": "main_page",
            "media_room": "media_room_page",
            "precut": "precut_page",
            "intro_video_room": "intro_video_page",
            "shutterstock": "download_from_ss_page",
            "getty_image": "getty_image_page",
            "title_designer": "title_designer_page",
            "timeline_operation": "timeline_operation_page",
            "tips_area": "tips_area_page",
            "playback_window": "playback_window_page",
            "Produce": "produce_page",
            "Import_Downloaded_Media_From_CL": "import_media_from_cloud_page",
            "Title_Room": "title_room_page",
            "DownloadFromCLDZ": "download_from_cl_dz_page",
            "pip_designer": "pip_designer_page",
            "PIP_Room": "pip_room_page",
            "Shape_Designer": "shape_designer_page",
            "particle_room": "particle_room_page",
            "particle_designer": "particle_designer_page",
            "Mask_Designer": "mask_designer_page",
            "VideoCollageDesigner": "video_collage_designer_page",
            "Trim": "trim_page",
            "Project_New": "project_new_page",
            "library_preview": "library_preview_page",
            "project_room": "project_room_page",
            "Effect_Room": "effect_room_page",
            "Effect_Settings": "effect_settings_page",
            "Audio_Mixing_Room": "audio_mixing_room_page",
            "Preferences_Page": "preferences_page",
            "Voice_Over_Recording_Room": "voice_over_recording_page",
            "Subtitle_Room": "subtitle_room_page",
            "Blending": "blending_mode_page",
            "Crop_Image": "crop_image_page",
            "Pan_Zoom": "pan_zoom_page",
            "Crop_Zoom_Pan": "crop_zoom_pan_page",
            "Video_speed_page": "video_speed_page",
            "Audio_Editing": "audio_editing_page",
            "FixEnhance": "fix_enhance_page",
            "Motion_Tracker": "motion_tracker_page",
            "KeyFrame_Page": "keyframe_room_page",
            "Transition_Room": "transition_room_page",
        }